In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
data = load_iris()
df = pd.DataFrame(data.data, columns=data.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [3]:
X = df.values
y = data.target
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30)

In [5]:
def euclidean(row1,row2):
    dist = np.sqrt(np.sum((np.array(row1)-np.array(row2))**2))
    return dist

### passing test row as a single data point vector - one at a time

In [6]:
##### if passing test row as a single data point vector - one at a time #####

def KNN(X_train,x,n,y_train):
    dist = []
    for i,r in enumerate(X_train):
        d = euclidean(r,x)
        dist.append((i,d))
    dist.sort(key = lambda tup :tup[1])
    
    n_neighbors = dist[:n]
    
    neigh_index = [x[0] for x in n_neighbors]
    
    neigh_classes = y_train[neigh_index]
    
    predicted = max(set(neigh_classes),key=list(neigh_classes).count)
    
    return predicted

In [7]:
predict = KNN(X_train,[5.6,4.9,3.2,3.1],5,y_train)
predict

1

### best version - entire train and test data as vector

In [8]:
def KNN(X_train,test,n,y_train):
    prediction = []
    for i,r in enumerate(test):
        dist = np.array([euclidean(r,x) for x in X_train])
        #dist.append((i,d))
        dist = dist.argsort()

        neigh_index = dist[:n]
        #print(neigh_index)
        #neigh_index = [x[0] for x in n_neighbors]

        neigh_classes = [y_train[r] for r in neigh_index]
        #print(neigh_classes)

        predicted = max(set(neigh_classes),key = neigh_classes.count)
        #print(predicted)
        prediction.append(predicted)
    
    return prediction
    

In [9]:
predict = KNN(X_train,X_test,8,y_train)
predict

[0,
 0,
 0,
 1,
 0,
 0,
 2,
 2,
 1,
 2,
 2,
 1,
 0,
 1,
 0,
 2,
 2,
 2,
 2,
 1,
 1,
 0,
 1,
 2,
 1,
 2,
 0,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 2,
 2,
 1,
 1,
 1,
 0]

In [10]:
def accuracy(y_actual,pred):
    '''
    count = 0
    for i in range(len(y_actual)):
        if y_actual[i]==pred[i]:
            count += 1
    perc = round(count/len(y_actual),4)
    '''
    ################# alternate #################
    perc = round((y_actual == pred).sum()/len(y_test),4)
    #############################################
    print("Accuracy : ",(perc)*100,"%")

In [11]:
accuracy(y_test,predict)

Accuracy :  97.78 %


### testing 

In [12]:
o = [1,2,1,1,1,3,4,3,2,2,3,2,2,4]

In [13]:
from collections import Counter
Counter(o).most_common()[0][0]

2

In [14]:
np.unique(o,return_counts=True)

(array([1, 2, 3, 4]), array([4, 5, 3, 2]))

In [15]:
np.unique(o,return_counts=True)[0]

array([1, 2, 3, 4])

In [22]:
np.unique(o,return_counts=True)[1]

array([4, 5, 3, 2])

In [18]:
np.argmax(np.unique(o,return_counts=True)[1])

1

In [23]:
np.unique(o,return_counts=True)[0][np.argmax(np.unique(o,return_counts=True)[1])]

2

In [24]:
max(set(o),key=list(o).count)

2